language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew clean build --scan -s
  - ./gradlew clean jacocoTestReport --scan -s

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
